# =============================================================================
# Saga Orchestration Service Helm Chart Values
# =============================================================================

# =============================================================================
# 이미지 설정
# =============================================================================
image:
  repository: octacloud/saga-orchestration-service
  tag: "419c99e6357e402a617057fe6836a0e7a677815f-18614370502"
  pullPolicy: IfNotPresent

# =============================================================================
# 서비스 설정
# =============================================================================
service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

# =============================================================================
# 배포 설정
# =============================================================================
replicaCount: 1

# =============================================================================
# 리소스 설정
# =============================================================================
resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 50m
    memory: 256Mi

# =============================================================================
# 헬스 체크 설정
# =============================================================================
livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: 8080
  initialDelaySeconds: 300
  periodSeconds: 30
  failureThreshold: 5
  timeoutSeconds: 10

readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: 8080
  initialDelaySeconds: 300
  periodSeconds: 30
  failureThreshold: 5
  timeoutSeconds: 10

# =============================================================================
# 환경 변수 설정
# =============================================================================
env:
  # Database configuration
  RDB_USERNAME: "monguser"
  RDB_PASSWORD: "mongpassword123"
  RDB_URL: "jdbc:mysql://localhost:3306/mong-saga?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
  
  # Kafka configuration
  KAFKA_BOOTSTRAP_SERVERS: "pkc-gq2xn.asia-northeast3.gcp.confluent.cloud:9092"
  KAFKA_SASL_MECHANISM: "PLAIN"
  KAFKA_SECURITY_PROTOCOL: "SASL_SSL"
  
  # Logging
  LOG_LEVEL: "INFO"
  LOG_PROFILE: "text"

# =============================================================================
# 서비스 계정 설정
# =============================================================================
serviceAccount:
  create: true
  name: ""

# =============================================================================
# ConfigMap 설정
# =============================================================================
configMap:
  create: true
  name: ""

# =============================================================================
# Secret 설정
# =============================================================================
secrets:
  create: true
  name: ""
  # 민감정보는 Sealed Secrets로 관리합니다. (빈 값 유지)
  KAFKA_SASL_USERNAME: ""
  KAFKA_SASL_PASSWORD: ""

sealedSecrets:
  enabled: true
  encryptedData:
    # 현재 클러스터의 공개키로 암호화된 Kafka 인증 정보
    KAFKA_SASL_USERNAME: "AgDmONL2ciH8z9fjx/t514OwhaP0+6YzLWn6V6FU/0tBdP2/OQm7K+P+X95kX91C5kyLKzP63LxpP5+P0RZ+8AWSfnPRhmqmJGLaSsxxa11EVO33iZDRhDskgR2tDjj4L63rQl5nmcb0ZvI1RnOj+I+LDpM6g9KUpXckcNyoQfXZ5VoFxiX2HcIE/bC8xL75ZatAxowcfFWmb3a9W8EtRyD+pER3BGtHPHunDkhn9SVNqUf4L1r1qB9ZATFp//O09NanNjcmzyPP0vESjtd9YBHmxRT4uhSjMeztBAZMr0BulhLWl7+676wbkGBnT4fycfStys2mXBzxAxaYEUfw3v5JG9aZXR7K5yTH0pYiLOIpSg4zcCcJxbmyHkvtHrQUbB9tDrU2PkGz/VuXy8xdjp5rcWWN0XAczp/dhBe4zz37WO7oI8cpdXHR0eBSruWkcFNTqzSqVybcihup7rlNbiQDd/KF69EtjS8rXNWGT9LAS5duA8BgGuzWcyqvTMlpgdq53udpkf3iuyWZokHoC0rH9rqYnju/mLRpOoK8sIvzaV2A0gKbyrLSVNNQsWlHX8xU9zxVYrm1W65ooCRzUBLhUK2jB3Zi0nV/u9w41qg/O4NS2Yy7DjBrtvGlbgkuC5Q/n0lbZwMcgv5mOH/zVZCukuvFhCYbq2mqjC/DmrVW58bcoTfPwTkpmpunbV/NTWmdxhpDRhJdnqRAUn7qWN8l"
    KAFKA_SASL_PASSWORD: "AgAfc+mmTH3NqEzLKfF9G8OJkBJhUFS26HvdqNC8xtDOapQdRYrcocPv47NpQTG/6dpYrZPFWKJJVva4h50S57qygohNygtgsBO6ipoXMWr+FTofKtrIIgZm3+6jK+CV1Vc/uB/eTBn/o4/JSnznFXDjPIzowAljbMYP+q4wEaYgHiQRT/jLvlp3jy+R1pGlwzMEBCYbHTFAuU1JZlMkdunP6nuT0eNQ7bwQPen5CY8yVuiVb5RHvFImVsVb21yP2ZlLDbfESs4FACM9NeZhrcqdCOb4y3cq6ebDZANR6YOVwM2nzOo3kjKY8BsjXO5qK0v1BrrA+01YOeF42x/VBvqIkUgb9UWSGqA/f2ivNYvJpjFmW4jVLv52WAbFacfb3PQ5zKPn/2wSVAa5iI7MtKxdQPjLXNfYYC0Bg9AzJbDFMaZauDDCxhvf/CoiKHuSOy7+5LcEDY2Je9OqmR0DVYwhQuwZyEv3U/o0LCR3XltaWnY1QbIOjkmHvd1HU2QqIwQouDO1g/wE5+6jGOAIhJ/MotuWPOiWaMq50ditWS0w7ncdo8KH0IG3WXDYi1JkWcajcG3znWBehkTzS2m3RBir7Ful2mJH+g1QEVoLMik8POz3VmmOkp4zE5GB3KE4OdaYNKawLBVfERiPs0OcfkSFZmL03gzh5YCeJ4TRhlL1kdThQf41cLcKKZC60Ph/BToZ4pizEZ21YHHJFGAWIPqxLLPAGT7H1Nt/GMQpET63xiBOuWWrLjYTtv2LarASVAduPmvhkYE5RlxgkrqtjF3x"

# =============================================================================
# Ingress 설정
# =============================================================================
ingress:
  enabled: false  # Saga orchestration service는 내부 서비스이므로 ingress 불필요

# =============================================================================
# 노드 선택자
# =============================================================================
nodeSelector: {}

# =============================================================================
# 톨러레이션
# =============================================================================
tolerations: []

# =============================================================================
# 어피니티
# =============================================================================
affinity: {}

# =============================================================================
# Cloud SQL Proxy 설정
# =============================================================================
cloudSqlProxy:
  enabled: true
  image: gcr.io/cloudsql-docker/gce-proxy:latest
  port: 3306
  instance: mong-develop:asia-northeast3:mong-mysql

# =============================================================================
# 추가 설정
# =============================================================================
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
imagePullSecrets: []

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70

lifecycle: {}
